controller:
  kind: DaemonSet
  allowSnippetAnnotations: true
  ingressClass: nginx
  ingressClassByName: true
  ingressClassResource:
    name: nginx
    enabled: true
    controllerValue: k8s.io/ingress-nginx
  service:
    annotations:
      metallb.io/address-pool: ingress
rbac:
  create: true
