---
apiVersion: v1
kind: Service
metadata:
  labels:
    lsst.io/role: logging
    lsst.io/component: fluent-bit
    lsst.io/env: external
    lsst.io/project: o11y
  name: fluent-bit-external-loadbalancer
spec:
  loadBalancerIP: 139.229.144.46
  ports:
  - name: rsyslog-udp
    port: 5140
    protocol: UDP
    targetPort: 5140
  - name: rsyslog-tcp
    port: 5140
    protocol: TCP
    targetPort: 5140
  - name: firewall-udp
    port: 5141
    protocol: UDP
    targetPort: 5141
  - name: firewall-tcp
    port: 5141
    protocol: TCP
    targetPort: 5141
  - name: netlog-udp
    port: 5142
    protocol: UDP
    targetPort: 5142
  - name: netlog-tcp
    port: 5142
    protocol: TCP
    targetPort: 5142
  selector:
    lsst.io/role: logging
    lsst.io/component: fluent-bit
    lsst.io/env: external
    lsst.io/project: o11y
  type: LoadBalancer
