---
hostname: rancher.dev.lsst.org
ingress:
  enabled: true
  ingressClassName: nginx
  tls:
    source: secret
  extraAnnotations:
    cert-manager.io/cluster-issuer: letsencrypt
extraEnv:
  # version strings from https://github.com/rancher/charts/tree/dev-v2.9/charts/fleet
  - name: CATTLE_FLEET_MIN_VERSION
    value: 106.0.0+up0.12.0
