---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rook-ceph-rgw-ingress
  namespace: rook-ceph
  annotations:
    cert-manager.io/issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
spec:
  tls:
  - hosts:
    - s3.ls.lsst.org
    secretName: rook-ceph-rgw-ingress-tls
  rules:
  - host: s3.ls.lsst.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rook-ceph-rgw-lfa
            port:
              number: 80
