---
# yamllint disable rule:quoted-strings
name: helm chart lint

"on":
  - push

jobs:
  chart-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: azure/setup-helm@v4.3.1
        with:
          version: 3.19.2

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25

      - name: helm chart lint
        run: go run ./utils/chart-lint.go
